# Generated by Django 4.1.5 on 2023-09-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_hommephoto_image_femmephoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="femme",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("Strings", "Strings"),
                    ("Soutien-gorges", "Soutien-gorges"),
                    ("Cullotes", "Cullotes"),
                ],
                default="Strings",
                max_length=50,
            ),
        ),
    ]
