# Generated by Django 4.1.5 on 2023-09-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_femme_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="femme",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("TOUT", "TOUT"),
                    ("Strings", "Strings"),
                    ("Soutien-gorges", "Soutien-gorges"),
                    ("Cullotes", "Cullotes"),
                ],
                default="TOUT",
                max_length=50,
            ),
        ),
    ]
