# Generated by Django 4.1.5 on 2023-09-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_homme_product_type_alter_femme_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homme",
            name="product_type",
            field=models.CharField(
                choices=[("Boxers", "Boxers"), ("Shorts", "Shorts")], max_length=50
            ),
        ),
    ]
