# Generated by Django 4.1.5 on 2023-09-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_homme_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homme",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("Boxers", "Boxers"),
                    ("Shorts", "Shorts"),
                    ("Extras", "Extras"),
                ],
                default="Boxers",
                max_length=50,
            ),
        ),
    ]
