# Generated by Django 4.1.5 on 2023-10-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="Homme",
            new_name="homme",
        ),
    ]
