# Generated by Django 4.1.5 on 2023-10-03 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_remove_cart_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.product",
            ),
        ),
    ]
