# Generated by Django 4.1.5 on 2023-10-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_productphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_type",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("homme", "Homme"), ("femme", "Femme")], max_length=10
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
