# Generated by Django 4.1.5 on 2023-10-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_alter_product_product_type_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("Boxers", "Boxers"),
                    ("Shorts", "Shorts"),
                    ("Extras", "Extras"),
                    ("Strings", "Strings"),
                    ("Ensembles", "Ensembles"),
                    ("Cullotes", "Cullotes"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
